"""
SentinEV - Agent State Management
Shared state for LangGraph multi-agent workflow
"""

from typing import Dict, List, Optional, Any, TypedDict, Annotated
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
import operator


class AgentMode(Enum):
    """Operating modes for the agent system."""

    MONITORING = "monitoring"  # Normal real-time monitoring
    ALERT = "alert"  # Anomaly detected, handling in progress
    FAULT_INJECTION = "fault_injection"  # Testing mode
    MAINTENANCE = "maintenance"  # Scheduled maintenance mode
    EMERGENCY = "emergency"  # Critical failure detected


class MessageRole(Enum):
    """Role of message sender."""

    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    AGENT = "agent"


@dataclass
class AgentMessage:
    """Message in the conversation history."""

    role: MessageRole
    content: str
    timestamp: datetime = field(default_factory=datetime.now)
    agent_name: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class VehicleContext:
    """Context about the current vehicle being analyzed."""

    vehicle_id: str
    driver_profile: str = "normal"
    current_telemetry: Dict[str, float] = field(default_factory=dict)
    historical_summary: Dict[str, Any] = field(default_factory=dict)
    active_faults: List[str] = field(default_factory=list)
    model_trained: bool = False


@dataclass
class AnomalyAlert:
    """Alert generated by anomaly detection."""

    alert_id: str
    timestamp: datetime
    vehicle_id: str
    anomaly_type: str
    severity: str
    failure_risk_pct: float
    affected_components: List[str]
    recommended_action: str
    acknowledged: bool = False
    resolved: bool = False


class AgentState(TypedDict):
    """
    Shared state for LangGraph workflow.

    This state is passed between agents and updated throughout the workflow.
    """

    # Session info
    session_id: str
    mode: str  # AgentMode value
    current_agent: str

    # Vehicle context
    vehicle_id: str
    driver_profile: str
    current_telemetry: Dict[str, float]

    # Anomaly detection results
    is_anomaly: bool
    anomaly_score: float
    anomaly_type: str
    severity: str
    failure_risk_pct: float
    time_to_failure_hours: Optional[float]
    affected_components: List[str]
    contributing_factors: List[Dict[str, Any]]

    # Scoring
    score_delta: int
    total_score: int
    scoring_events: List[Dict[str, Any]]
    feedback_text: str
    badges_earned: List[str]

    # Alerts and actions
    active_alerts: Annotated[List[Dict], operator.add]  # Accumulates alerts
    pending_actions: List[Dict[str, Any]]

    # Conversation
    messages: Annotated[List[Dict], operator.add]  # Accumulates messages

    # RAG context
    rag_context: List[Dict[str, Any]]

    # UEBA tracking
    agent_actions_log: Annotated[List[Dict], operator.add]  # Audit trail
    ueba_alerts: List[Dict[str, Any]]

    # Workflow control
    should_continue: bool
    next_agent: Optional[str]


def create_initial_state(vehicle_id: str, session_id: str = None) -> AgentState:
    """Create initial agent state for a new session."""
    import uuid

    return {
        "session_id": session_id or str(uuid.uuid4()),
        "mode": AgentMode.MONITORING.value,
        "current_agent": "orchestrator",
        "vehicle_id": vehicle_id,
        "driver_profile": "normal",
        "current_telemetry": {},
        "is_anomaly": False,
        "anomaly_score": 0.0,
        "anomaly_type": "normal",
        "severity": "low",
        "failure_risk_pct": 0.0,
        "time_to_failure_hours": None,
        "affected_components": [],
        "contributing_factors": [],
        "score_delta": 0,
        "total_score": 0,
        "scoring_events": [],
        "feedback_text": "",
        "badges_earned": [],
        "active_alerts": [],
        "pending_actions": [],
        "messages": [],
        "rag_context": [],
        "agent_actions_log": [],
        "ueba_alerts": [],
        "should_continue": True,
        "next_agent": None,
    }


def state_to_dict(state: AgentState) -> Dict[str, Any]:
    """Convert state to serializable dictionary."""
    return dict(state)
